In [2]:
import numpy as np

X = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55], [111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555]])
Y = np.array([[1, 2], [11, 22], [111, 222], [1111, 2222]])
#X = np.asarray(X, dtype=np.float32)
X

array([[   1,    2,    3,    4,    5],
       [  11,   22,   33,   44,   55],
       [ 111,  222,  333,  444,  555],
       [1111, 2222, 3333, 4444, 5555]])

In [14]:
Y

array([[   1,    2],
       [  11,   22],
       [ 111,  222],
       [1111, 2222]])

In [15]:
X[0:2, :]

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [16]:
X_seq = []
X_seq.append(X[0:2, :])
X_seq

[array([[ 1,  2,  3,  4,  5],
        [11, 22, 33, 44, 55]])]

In [12]:
Y_seq = []
Y_seq.append(Y[2-1,:])
Y_seq

[array([11, 22])]

In [21]:
X_seq = []
Y_seq = []
X_seq.append(np.concatenate(X[0:2,:]).tolist())
Y_seq.append(Y[2-1,:].tolist())
print("Primero: ", X_seq, Y_seq)
X_seq.append(np.concatenate(X[1:3,:]).tolist())
Y_seq.append(Y[3-1,:].tolist())
print("Segundo: ", X_seq, Y_seq)
X_seq.append(np.concatenate(X[2:4,:]).tolist())
Y_seq.append(Y[4-1,:].tolist())
print("Tercero: ", X_seq, Y_seq)


Primero:  [[1, 2, 3, 4, 5, 11, 22, 33, 44, 55]] [[11, 22]]
Segundo:  [[1, 2, 3, 4, 5, 11, 22, 33, 44, 55], [11, 22, 33, 44, 55, 111, 222, 333, 444, 555]] [[11, 22], [111, 222]]
Tercero:  [[1, 2, 3, 4, 5, 11, 22, 33, 44, 55], [11, 22, 33, 44, 55, 111, 222, 333, 444, 555], [111, 222, 333, 444, 555, 1111, 2222, 3333, 4444, 5555]] [[11, 22], [111, 222], [1111, 2222]]


In [18]:
np.array(X_seq)


array([[   1,    2,    3,    4,    5,   11,   22,   33,   44,   55],
       [  11,   22,   33,   44,   55,  111,  222,  333,  444,  555],
       [ 111,  222,  333,  444,  555, 1111, 2222, 3333, 4444, 5555]])

In [23]:
np.array(Y_seq)

array([[  11,   22],
       [ 111,  222],
       [1111, 2222]])

In [27]:
X_seq = []
Y_seq = []
X_seq.append(np.concatenate(X[0:1,:]).tolist())
Y_seq.append(Y[1-1,:].tolist())
print("Primero: ", X_seq, Y_seq)
X_seq.append(np.concatenate(X[1:2,:]).tolist())
Y_seq.append(Y[2-1,:].tolist())
print("Segundo: ", X_seq, Y_seq)
X_seq.append(np.concatenate(X[2:3,:]).tolist())
Y_seq.append(Y[3-1,:].tolist())
print("Tercero: ", X_seq, Y_seq)
print("\n\n")
print(np.array(X_seq))
print(np.array(Y_seq))

Primero:  [[1, 2, 3, 4, 5]] [[1, 2]]
Segundo:  [[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]] [[1, 2], [11, 22]]
Tercero:  [[1, 2, 3, 4, 5], [11, 22, 33, 44, 55], [111, 222, 333, 444, 555]] [[1, 2], [11, 22], [111, 222]]



[[  1   2   3   4   5]
 [ 11  22  33  44  55]
 [111 222 333 444 555]]
[[  1   2]
 [ 11  22]
 [111 222]]


In [28]:
X_seq = []
Y_seq = []
X_seq.append(np.concatenate(X[0:3,:]).tolist())
Y_seq.append(Y[3-1,:].tolist())
print("Primero: ", X_seq, Y_seq)
X_seq.append(np.concatenate(X[1:4,:]).tolist())
Y_seq.append(Y[4-1,:].tolist())
print("Segundo: ", X_seq, Y_seq)
# X_seq.append(np.concatenate(X[2:5,:]).tolist())
# Y_seq.append(Y[5-1,:].tolist())
# print("Tercero: ", X_seq, Y_seq)
print("\n\n")
print(np.array(X_seq))
print(np.array(Y_seq))

Primero:  [[1, 2, 3, 4, 5, 11, 22, 33, 44, 55, 111, 222, 333, 444, 555]] [[111, 222]]
Segundo:  [[1, 2, 3, 4, 5, 11, 22, 33, 44, 55, 111, 222, 333, 444, 555], [11, 22, 33, 44, 55, 111, 222, 333, 444, 555, 1111, 2222, 3333, 4444, 5555]] [[111, 222], [1111, 2222]]



[[   1    2    3    4    5   11   22   33   44   55  111  222  333  444
   555]
 [  11   22   33   44   55  111  222  333  444  555 1111 2222 3333 4444
  5555]]
[[ 111  222]
 [1111 2222]]


Otra prueba

In [39]:
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[4, 5, 6, 7, 8], [4, 5, 6, 7, 8]])
c = np.array([[9, 10], [9, 10], [9, 10], [9, 10], [9, 10], [9, 10]])

In [40]:
d = np.array([])
d = np.append(d, a)
d =np.append(d, b)
d = np.append(d, c)
d

array([ 1.,  2.,  3.,  1.,  2.,  3.,  1.,  2.,  3.,  1.,  2.,  3.,  4.,
        5.,  6.,  7.,  8.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  9., 10.,
        9., 10.,  9., 10.,  9., 10.,  9., 10.])

In [2]:
res = []
a = [1, 2, 3, 4]
b = [4, 5, 6, 7]
res.append(a)
res.append(b)
res

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [ ]:
import json
a=[{"a":1, "b":2}
   ,{"a":11, "b":22}
   ,{"a":33, "b":3}
]

aa = [x["b"] for x in a]
print(json.dumps(aa, indent=2))

In [35]:
X = np.array([[ 1.2, -0.4,  2,  3.1], [ 1.2,  0.4,  4,  1. ]])
voca = np.arange(np.min(X), np.max(X)+1, 0.1).round(1)
print(f"X{X.shape} = {X}")
print(voca)

X(2, 4) = [[ 1.2 -0.4  2.   3.1]
 [ 1.2  0.4  4.   1. ]]
[-0.4 -0.3 -0.2 -0.1 -0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9
  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3
  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7
  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9]


In [36]:
int(np.where(voca==X[1][2])[0])

44

In [37]:
i=0
res=[]
while i < X.shape[0]:
    j=0
    lin = []    
    while j < X.shape[1]:
        aux = int(np.where(voca==X[i][j])[0])
        print(f"i:{i}, j:{j}, aux:{aux}")
        lin.append(aux)
        j=j+1
    res.append(lin)
    i=i+1

i:0, j:0, aux:16
i:0, j:1, aux:0
i:0, j:2, aux:24
i:0, j:3, aux:35
i:1, j:0, aux:16
i:1, j:1, aux:8
i:1, j:2, aux:44
i:1, j:3, aux:14


In [39]:
print(X)
print(np.array(res))

[[ 1.2 -0.4  2.   3.1]
 [ 1.2  0.4  4.   1. ]]
[[16  0 24 35]
 [16  8 44 14]]


In [5]:
import os

dir_output = f'transformers/eval/only_velocity/normalized'
asd = dir_output.replace('eval', 'opt')
print(asd)

print(os.path.join(asd, 'params/loco/mua', 'nombre_archivo'))

transformers/opt/only_velocity/normalized
transformers/opt/only_velocity/normalized/params/loco/mua/nombre_archivo


In [6]:
/home/paty/tesis/tesis_transformers/my_transformers/opt/only_velocity/normalized/best_weights/indy/sua/indy_20161017_02_baks_rounded_1.pt

TypeError: Object dtype dtype('O') has no native HDF5 equivalent

In [1]:
import os

dir_output = 'my_transformers/opt/only_velocity/normalized/best_weights/indy/sua'
file_name = 'indy_20161017_02_baks_rounded_1.h5'
best_weights_path = os.path.join(f'{dir_output}', f"{file_name[:-3]}_best.pt")

print("dir_output", dir_output)
print("file_name", file_name)
print("best_weights_path", best_weights_path)

dir_output my_transformers/opt/only_velocity/normalized/best_weights/indy/sua
file_name indy_20161017_02_baks_rounded_1.h5
best_weights_path my_transformers/opt/only_velocity/normalized/best_weights/indy/sua/indy_20161017_02_baks_rounded_1_best.pt


In [9]:
if 'best' in best_weights_path:
    print("si")
else:
    print("no")

si


In [21]:
import numpy as np

f1 = np.array([[3, 5.5, 0], [1.1, 6, 3.3], [8, 8, 4], [4.3, 7.2, 9.1], [2.2, 2, 0]])
f2 = np.array([[3.5, 5, 1, 8.9], [1, 2.1, 6, 7]])
f3 = np.array([[3, 5, 6, 7.8, 4], [9, 8, 7.5, 4, 4], [2.3, 5, 8, 3, 4]])

print(f"largos  f1: {len(f1)} {len(f1[0])}; f2: {len(f2)} {len(f2[0])}; f3: {len(f3)} {len(f3[0])}")

# Agrupando archivos en una sola lista
Xs = []
max_cols = 0
min_cols = 999999999999999999999

Xs.append(f1)
Xs.append(f2)
Xs.append(f3)
print(Xs)
# calculando cantidad columnas máximo y mínimo de todos los archivos
for X in Xs:
    if max_cols < len(X[0]):
        max_cols = len(X[0]) 
    if min_cols > len(X[0]):
        min_cols = len(X[0])
print(f"max_cols: {max_cols}, min_cols: {min_cols}")


largos  f1: 5 3; f2: 2 4; f3: 3 5
[array([[3. , 5.5, 0. ],
       [1.1, 6. , 3.3],
       [8. , 8. , 4. ],
       [4.3, 7.2, 9.1],
       [2.2, 2. , 0. ]]), array([[3.5, 5. , 1. , 8.9],
       [1. , 2.1, 6. , 7. ]]), array([[3. , 5. , 6. , 7.8, 4. ],
       [9. , 8. , 7.5, 4. , 4. ],
       [2.3, 5. , 8. , 3. , 4. ]])]
max_cols: 5, min_cols: 3


In [27]:
# Las columnas deben ser el mismo número para todos
# Usando padding, rellenando con 0 espacios faltantes
i = 0
while i < len(Xs):
    if len(Xs[i][0]) != max_cols:
        resto = max_cols - len(Xs[i][0])
        Xs[i] = np.pad(Xs[i], (0,resto), constant_values=(0))
        Xs[i] = Xs[i][:-resto]
    i=i+1
print(Xs)    

[array([[3. , 5.5, 0. , 0. , 0. ],
       [1.1, 6. , 3.3, 0. , 0. ],
       [8. , 8. , 4. , 0. , 0. ],
       [4.3, 7.2, 9.1, 0. , 0. ],
       [2.2, 2. , 0. , 0. , 0. ]]), array([[3.5, 5. , 1. , 8.9, 0. ],
       [1. , 2.1, 6. , 7. , 0. ]]), array([[3. , 5. , 6. , 7.8, 4. ],
       [9. , 8. , 7.5, 4. , 4. ],
       [2.3, 5. , 8. , 3. , 4. ]])]


In [13]:
# Las columnas deben ser el mismo número para todos
# Truncando
i = 0
while i < len(Xs):
    if len(Xs[i][0]) != min_cols:
        resto = len(Xs[i][0]) - min_cols
        temp = []
        for elem in Xs[i]:
            elem = list(elem[:-resto])
            temp.append(elem)
        Xs[i] = np.array(temp)
    i=i+1
print(Xs) 

[array([[3. , 5.5, 0. ],
       [1.1, 6. , 3.3],
       [8. , 8. , 4. ],
       [4.3, 7.2, 9.1],
       [2.2, 2. , 0. ]]), array([[3.5, 5. , 1. ],
       [1. , 2.1, 6. ]]), array([[3. , 5. , 6. ],
       [9. , 8. , 7.5],
       [2.3, 5. , 8. ]])]


In [28]:
print(Xs)
print("---------------")
res = []
for elem in Xs:
    for e in elem:
        t = e.tolist()
        res.append(t)
print(res)
print(np.array(res))

[array([[3. , 5.5, 0. , 0. , 0. ],
       [1.1, 6. , 3.3, 0. , 0. ],
       [8. , 8. , 4. , 0. , 0. ],
       [4.3, 7.2, 9.1, 0. , 0. ],
       [2.2, 2. , 0. , 0. , 0. ]]), array([[3.5, 5. , 1. , 8.9, 0. ],
       [1. , 2.1, 6. , 7. , 0. ]]), array([[3. , 5. , 6. , 7.8, 4. ],
       [9. , 8. , 7.5, 4. , 4. ],
       [2.3, 5. , 8. , 3. , 4. ]])]
---------------
[[3.0, 5.5, 0.0, 0.0, 0.0], [1.1, 6.0, 3.3, 0.0, 0.0], [8.0, 8.0, 4.0, 0.0, 0.0], [4.3, 7.2, 9.1, 0.0, 0.0], [2.2, 2.0, 0.0, 0.0, 0.0], [3.5, 5.0, 1.0, 8.9, 0.0], [1.0, 2.1, 6.0, 7.0, 0.0], [3.0, 5.0, 6.0, 7.8, 4.0], [9.0, 8.0, 7.5, 4.0, 4.0], [2.3, 5.0, 8.0, 3.0, 4.0]]
[[3.  5.5 0.  0.  0. ]
 [1.1 6.  3.3 0.  0. ]
 [8.  8.  4.  0.  0. ]
 [4.3 7.2 9.1 0.  0. ]
 [2.2 2.  0.  0.  0. ]
 [3.5 5.  1.  8.9 0. ]
 [1.  2.1 6.  7.  0. ]
 [3.  5.  6.  7.8 4. ]
 [9.  8.  7.5 4.  4. ]
 [2.3 5.  8.  3.  4. ]]


In [8]:
a = "['indy_20161017_02_baks_rounded_1.h5', 'indy_20160407_02_baks_rounded_1.h5']"
b = a.replace('"', '')
sopa = []
sopa.append(a[1:-1])
print(sopa)
print(b)
type(b)

["'indy_20161017_02_baks_rounded_1.h5', 'indy_20160407_02_baks_rounded_1.h5'"]
['indy_20161017_02_baks_rounded_1.h5', 'indy_20160407_02_baks_rounded_1.h5']


str

In [10]:
c = ['indy_20161017_02_baks_rounded_1.h5', 'indy_20160407_02_baks_rounded_1.h5']
type(c)

print(b == c)


False


In [11]:
d = "indy_20160407_02_baks_rounded_1.h5, indy_20160419_01_baks_rounded_1.h5, indy_20160921_01_baks_rounded_1.h5, indy_20161017_02_baks_rounded_1.h5, indy_20161212_02_baks_rounded_1.h5"
e = d.split(", ")
print(e)
type(e)



['indy_20161017_02_baks_rounded_1.h5', 'indy_20160407_02_baks_rounded_1.h5']


list

In [5]:
import os

for dataset in os.listdir('data/rounded/loco'):
    print(dataset)

loco_20170216_02_baks_rounded_1.h5
loco_20170228_02_baks_rounded_1.h5
loco_20170217_02_baks_rounded_1.h5
loco_20170214_02_baks_rounded_1.h5
loco_20170302_02_baks_rounded_1.h5
loco_20170213_02_baks_rounded_1.h5
loco_20170210_03_baks_rounded_1.h5
loco_20170215_02_baks_rounded_1.h5
loco_20170227_04_baks_rounded_1.h5
loco_20170301_05_baks_rounded_1.h5


In [4]:
os.listdir('.')

['data',
 'eval',
 '__pycache__',
 'opt',
 'example.h5',
 'Untitled-1.ipynb',
 'vocabulary_test.py',
 'test.txt',
 'process_input.py',
 'model.py',
 'transformers_p.py',
 'opt_transformers.py',
 'best_params',
 'eval_transformers.py']